### ISSUE TITLE
UnpicklingError: A load persistent id instruction was encountered

### ISSUE THREAD

**Issue by gouxin666** [barbararoessle/dense_depth_priors_nerf#34]
Traceback (most recent call last):
  File "/home/lhs/project/nerf/dense_depth_priors_nerf-master/run_nerf.py", line 1104, in <module>
    run_nerf()
  File "/home/lhs/project/nerf/dense_depth_priors_nerf-master/run_nerf.py", line 1070, in run_nerf
    train_nerf(images, depths, valid_depths, poses, intrinsics, i_split, args, scene_sample_params, lpips_alex, gt_depths, gt_valid_depths)
  File "/home/lhs/project/nerf/dense_depth_priors_nerf-master/run_nerf.py", line 788, in train_nerf
    depths, valid_depths = complete_and_check_depth(images, depths, valid_depths, i_train, gt_depths_train, gt_valid_depths_train, \
  File "/home/lhs/project/nerf/dense_depth_priors_nerf-master/run_nerf.py", line 726, in complete_and_check_depth
    depths[i_train], valid_depths[i_train] = complete_depth(images[i_train], depths[i_train], valid_depths[i_train], \
  File "/home/lhs/project/nerf/dense_depth_priors_nerf-master/run_nerf.py", line 678, in complete_depth
    ckpt = torch.load(model_path)
  File "/home/lhs/.conda/envs/liao/lib/python3.10/site-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/lhs/.conda/envs/liao/lib/python3.10/site-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.

Hello, when reproducing, I first downloaded the depth_priors network model, then downloaded the scenes listed in the readme, and ran python3 run_nerf.py train with the above data --scene_id <scene, e.g. scene0710_00> --data_dir < directory containing the scenes> --depth_prior_network_path <path to depth prior checkpoint> --ckpt_dir <path to write checkpoints>But the above problem occurred. Is there a problem with the version of some files?

**Comment by zhanghaoyu816** [comment]
Hello, I have also encountered this problem when I try to reproduce the project. Do you solve this problem? Could you please tell me how to set the "--depth_prior_network_path "? (I have downloaded the depth completion model from the link provided by the author, and then unzip it to get a file folder "Archive")

**Comment by gouxin666** [comment]
> Hello, I have also encountered this problem when I try to reproduce the project. Do you solve this problem? Could you please tell me how to set the "--depth_prior_network_path "? (I have downloaded the depth completion model from the link provided by the author, and then unzip it to get a file folder "Archive")

The downloaded 'depth_priors network model' model does not need to be decompressed. Simply put the compressed package into the corresponding folder and then execute the command to solve this problem.
